jobs:
  build:
    runs-on: macos-latest
    steps:
    
    - name: Checkout Code
       uses: actions/checkout@v4

    - name: Select Xcode Version
       run: sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer

    - name: Show Xcode Schemes
        run: xcodebuild -list

    - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

    - name: Archive & Export IPA
        run: |
          xcodebuild clean archive \
            -scheme "CICDProject" \
            -project "CICDProject.xcodeproj" \
            -archivePath build/App.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/
