name: iOS Build & Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: List Files (Debugging)
        run: ls -la

      - name: Select Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json 2>/dev/null || echo '{}')
          if [ -z "$scheme_list" ] || [ "$scheme_list" = "{}" ]; then
            echo "Error: No schemes found. Check Xcode version or project settings."
            exit 1
          fi
          default=$(echo "$scheme_list" | ruby -r json -e '
            data = JSON.parse(STDIN.read)
            puts data.dig("project", "targets", 0) || "Unknown"
          ')
          if [ "$default" = "Unknown" ]; then
            echo "Error: Failed to parse scheme list."
            exit 1
          fi
          echo "$default" > default
          echo "Using default scheme: $default"

      - name: Build App
        run: |
          xcodebuild build-for-testing \
            -scheme "CICDProject" \
            -project "CICDProject.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -scheme "CICDProject" \
            -project "CICDProject.xcodeproj" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
