name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Run SwiftLint
        run: swiftlint --strict

      - name: Run SwiftFormat
        run: swiftformat . --lint

      - name: Build project
        run: xcodebuild -workspace CICDProject.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean build

      - name: Run tests
        run: xcodebuild test -workspace CICDProject.xcworkspace -scheme YourApp -destination 'platform=iOS Simulator,name=iPhone 14'
