name: iOS Build & Test Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

    

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Set Default Scheme
        run: echo "DEFAULT_SCHEME=CICDProject" >> $GITHUB_ENV

      - name: Build App
        run: |
          xcodebuild build-for-testing \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject1.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject1.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

    
