name: iOS Build & Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Set Default Scheme
        run: echo "DEFAULT_SCHEME=CICDProject" >> $GITHUB_ENV

      - name: Build App
        run: |
          xcodebuild build-for-testing \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Run Tests
        run: |
          xcodebuild test-without-building \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: build archive
        run: |
          xcodebuild -scheme "${{ env.DEFAULT_SCHEME }}" \
          -archivePath $RUNNER_TEMP/iamgroot.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          clean archive          

      - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/iamgroot.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build 


