name: iOS Build & Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Set Default Scheme
        run: echo "DEFAULT_SCHEME=CICDProject" >> $GITHUB_ENV

      - name: Build App
        run: |
          xcodebuild build-for-testing \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Run Tests with Code Coverage
        run: |
          xcodebuild test-without-building \
            -scheme "${{ env.DEFAULT_SCHEME }}" \
            -workspace "CICDProject.xcworkspace" \
            -destination "platform=iOS Simulator,name=iPhone 15" \
            -enableCodeCoverage YES  \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

      - name: Archive & Export IPA
        run: |
          xcodebuild archive \
            -scheme "CICDProject" \
            -project "CICDProject.xcodeproj" \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist ExportOptions.plist


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/








