name: iOS Build & Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: iOS Build & Test
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_15.3.app/Contents/Developer

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Set Default Scheme
        run: echo "DEFAULT_SCHEME=CICDProject" >> $GITHUB_ENV

      - name: Build and Archive IPA (iPhone)
        run: |
          xcodebuild archive \
            -scheme "CICDProject" \
            -project "CICDProject.xcodeproj" \
            -archivePath build/App.xcarchive \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/Release-iphoneos/ \
            -exportOptionsPlist ExportOptions.plist

      - name: Debug Build Folder
        run: ls -la build/

      - name: Upload IPA (iPhone)
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/Release-iphoneos/
