name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Verify Podfile
        run: ls -la

      - name: Create Podfile if missing
        run: |
          if [ ! -f Podfile ]; then
            pod init
          fi
          pod install --repo-update

      - name: Install dependencies
        run: |
          brew update
          brew install swiftformat swiftlint

      - name: Run SwiftLint
        run: |
          export PATH="/opt/homebrew/bin:$PATH"
          swiftlint --strict

      - name: Run SwiftFormat
        run: swiftformat . --lint

      - name: Verify Workspace
        run: ls -la

      - name: Build project
        run: xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' clean build

      - name: Run tests
        run: xcodebuild test -workspace YourApp.xcworkspace -scheme YourApp -destination 'platform=iOS Simulator,name=iPhone 14'
