name: iOS Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Debug Project Structure
        run: ls -R

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: List Xcode Schemes
        run: xcodebuild -list

      - name: Build and Archive IPA (iPhone)
        run: |
          xcodebuild archive \
            -scheme "CICDProject" \
            -project "CICDProject.xcodeproj" \
            -archivePath build/App.xcarchive \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/Release-iphoneos/ \
            -exportOptionsPlist ExportOptions.plist

      - name: Debug Build Folder
        run: ls -la build/

      - name: Upload IPA (iPhone)
        uses: actions/upload-artifact@v4
        with:
          name: iOS-App
          path: build/Release-iphoneos/
